server:
  port: 31200
spring:
  application:
    name: xc-service-manage-course
  datasource:
    druid:
      url: jdbc:mysql://192.168.25.129:3306/xc_course?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
      database: xc_cms

xuecheng:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 3000
    charset: UTF-8
    tracker_servers: 192.168.25.133:22122 #多个 trackerServer中间以逗号分隔

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.93:20000/eureka/

#课程预览页面配置
course-publish:
  cmsPage:
    siteId: 5a751fab6abb5044e0d19ea2
    templateId: 5ad9a24d68db5239b8fef199
    pageWebPath: /course/detail/
    pagePhysicalPath: /course/detail/
    dataUrl: http://localhost:31200/courseview/get/
  previewUrl: http://www.xuecheng.com/cms/preview/