server:
  port: 40100

spring:
  application:
    name: xc-server-search

xuecheng:
  elasticsearch:
    hostlist: 192.168.25.129:9200
    course:
      index: xc_course
      type: doc
      source_field: id,name,grade,mt,st,charge,valid,pic,qq,price,price_old,status,studymodel,teachmode,expires,pub_ time,start_time,end_time